server:
  port: 8080
  servlet:
    context-path: /microCloud

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mappers/*.xml
