server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  application:
    name: user-service-privoder-8080
mybatis:
  mapper-locations: classpath:mappers/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://xdd.com:1111/eureka/,http://xdd.cn:1112/eureka/
